### ISSUE TITLE
latest splitio-react package has issues with types import

### ISSUE THREAD

**Issue by nrutenberg-newrelic** [splitio/react-typescript-sdk-examples#18]
Importing of `SplitIO` from `@splitsoftware/splitio/types/splitio`, although it should be `@splitsoftware/splitio-react/types/splitio`.
Had to use a previous package version in order to run tsc.
The imports are:
<img width="1190" alt="Screen Shot 2021-07-25 at 22 48 43" src="https://user-images.githubusercontent.com/79189476/126911568-14b66e3f-39d6-4f53-a0c9-52cee5e5e8dd.png">

**Comment by EmilianoSanchez** [comment]
I am closing this issue for now. 

Yes, the `SplitIO` namespace cannot be imported as `import SplitIO from "@splitsoftware/splitio-react/types/splitio";`.
However, explicit import is unnecessary, as it is imported implicitly when importing any module from "@splitsoftware/splitio-react".
